package com.lucciano.ironssablecompat.mixin;

import dev.ryanhcode.sable.companion.SableCompanion;
import io.redspace.ironsspellbooks.capabilities.magic.MagicManager;
import io.redspace.ironsspellbooks.particle.TraceParticleOptions;
import net.minecraft.core.particles.ParticleOptions;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;
import net.minecraft.server.level.ServerLevel;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Projects all particle coordinates generated by Iron's Spells to the Real-World space.
 * 
 * Root cause: When a spell is cast on a Sable ship (sub-level space), particle coordinates
 * are generated in sub-level space (e.g. 500,000+ coordinates). Since standard Minecraft
 * particles are not projected to the real world by Sable's contraption rendering, they spawn
 * in the void and are invisible.
 * 
 * Fix: Intercept all particle spawns via MagicManager.spawnParticles and project their spawn
 * coordinates and destination vectors back to the Real World. This ensures particles are
 * visible and align perfectly with moving ships.
 */
@Mixin(value = MagicManager.class, remap = false)
public class MagicManagerMixin {

    @Inject(
        method = "spawnParticles(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/particles/ParticleOptions;DDDIDDDDZ)V",
        remap = false,
        at = @At("HEAD"),
        cancellable = true
    )
    private static void projectParticleCoordinates(Level level, ParticleOptions options, double x, double y, double z, int count, double deltaX, double deltaY, double deltaZ, double speed, boolean force, CallbackInfo ci) {
        Vec3 originalPos = new Vec3(x, y, z);
        Vec3 projectedPos = SableCompanion.INSTANCE.projectOutOfSubLevel(level, originalPos);
        
        if (options instanceof TraceParticleOptions traceOptions) {
            if (traceOptions.destination != null) {
                Vec3 originalDest = new Vec3(traceOptions.destination.x, traceOptions.destination.y, traceOptions.destination.z);
                Vec3 projectedDest = SableCompanion.INSTANCE.projectOutOfSubLevel(level, originalDest);
                traceOptions.destination.set((float) projectedDest.x, (float) projectedDest.y, (float) projectedDest.z);
            }
        }
        
        if (level instanceof ServerLevel serverLevel) {
            serverLevel.getServer().getPlayerList().getPlayers().forEach(player -> 
                serverLevel.sendParticles(player, options, force, projectedPos.x, projectedPos.y, projectedPos.z, count, deltaX, deltaY, deltaZ, speed)
            );
        }
        ci.cancel();
    }
}
